CREATE TYPE "public"."golongan_darah" AS ENUM('A', 'B', 'AB', 'O');--> statement-breakpoint
CREATE TYPE "public"."jenis_kelamin" AS ENUM('L', 'P');--> statement-breakpoint
CREATE TYPE "public"."kewarganegaraan" AS ENUM('WNI', 'WNA');--> statement-breakpoint
CREATE TYPE "public"."pendidikan" AS ENUM('SD/SEDERAJAT', 'SLTP/SEDERAJAT', 'SLTA/SEDERAJAT', 'DIPLOMA 1', 'DIPLOMA 2', 'STRATA 1', 'STRATA 2');--> statement-breakpoint
CREATE TYPE "public"."status_kawin" AS ENUM('KAWIN', 'CERAI', 'KAWIN TERCATAT', 'CERAI MATI');--> statement-breakpoint
CREATE TABLE "dusun" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dusun_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"upadted_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "kartu_keluarga" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kartu_keluarga_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nomor_kk" integer NOT NULL,
	"rt" integer NOT NULL,
	"rw" integer NOT NULL,
	"dusun_id" integer NOT NULL,
	"penduduk_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"upadted_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "kartu_keluarga_nomor_kk_unique" UNIQUE("nomor_kk")
);
--> statement-breakpoint
CREATE TABLE "agama" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "agama_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nama" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "penduduk" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "penduduk_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"parent_id" integer,
	"nama" varchar(100) NOT NULL,
	"nik" varchar(16) NOT NULL,
	"tempat_lahir" varchar(100),
	"tanggal_lahir" date NOT NULL,
	"jenis_kelamin" "jenis_kelamin" NOT NULL,
	"golongan_darah" "golongan_darah" NOT NULL,
	"pekerjaan" varchar(100) NOT NULL,
	"agama_id" integer NOT NULL,
	"role_id" integer,
	"status_kawin" "status_kawin" NOT NULL,
	"pendidikan" "pendidikan" NOT NULL,
	"kewarganegaraan" "kewarganegaraan" NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "penduduk_nik_unique" UNIQUE("nik")
);
--> statement-breakpoint
CREATE TABLE "role" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "kartu_keluarga" ADD CONSTRAINT "kartu_keluarga_penduduk_id_penduduk_id_fk" FOREIGN KEY ("penduduk_id") REFERENCES "public"."penduduk"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "penduduk" ADD CONSTRAINT "penduduk_parent_id_penduduk_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."penduduk"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "penduduk" ADD CONSTRAINT "penduduk_role_id_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."role"("id") ON DELETE no action ON UPDATE no action;